### ISSUE TITLE
Integrate this with lite-xl ?

### ISSUE THREAD

**Issue by franko** [takase1121/lite-fallback-fonts#2]
I was wondering if it make sense to bake this work into lite-xl.

Could you help me, @takase1121, to understand the problem that is solved by this plugin ? I loosely understood that for codepoints that are not present in a font you lookup for them in another font set. Is this enough to make lite work for CJK languages ? It means that you can view and modify files with CJK content ?

**Comment by takase1121** [comment]
The truth is this plugin barely works (and even breaks sometimes).
Calculating variable font width is very complicated, especially with
multiple fonts,not to mention due to how lua VM works this will also
consume a lot of resources. I really don't recommend integrating this to
lite-xl. If possible, we could investigate alternatives.

**Comment by franko** [comment]
Ok, thank you. If you come up with some idea for lite-xl don't hesitate.

Some things we may do in the C side if needed for improved efficiency. As long as we have a clear idea about what we want to do and it is sound and self-contained we can code it is C and integrate it with the editor. On the other side it would be important to accurately define the "scope" of what it does.
